import psycopg2
# conn = psycopg2.connect('dbname=kurz user=postgres password=fifi')
# cur = conn.cursor()
# # cur.execute("""CREATE TABLE test(s varchar(100));""")
# conn.commit()
# cur.close()
conn = psycopg2.connect('dbname=kurz user=postgres password=fifi')
cur = conn.cursor()
cur.execute("""INSERT INTO test VALUES ('aaa'), ('bbb');""")
conn.commit()
cur.execute("""SELECT * FROM test;""")
print(cur.fetchall())
cur.execute("""SELECT * FROM ucastnici;""")
print(cur.fetchall())